# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a59e8ad868d7d354f616cafca3cdb02c3ea5030dbe4a0b8a3558c9ffceedb25e6f045e38bd0985169f812f0622a3e1c69a23d776c830d2ac9c0b02ce30d1fe8

test:
  secret_key_base: 5e48b8ad53c9964cf70e67bd27cd745b7353d3f7591bcbe2fdc81f538dbc8b70135e281dcc42099d34f3b0ee56f60276f3110a76aa7b5069f92667953e357525

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
